version: "3.9"

services:
  db:
    containter_name: ${DB_NAME}
    image: postgres:17.6
    restart: always
    ports:
      - "${DB_PORT}:5432"
    enviroment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d